import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Iphone 15 | By Apple",
  description:
    "Discover the latest features of the Iphone 15, designed and manufactured by Apple. Learn about its cutting-edge technology, stunning design, and powerful performance. This webpage is generated by create next app, a modern development tool for building efficient and responsive web applications.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/assets/images/apple.svg" />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
